service: default
runtime: nodejs12
env: standard
env_variables:
  PORT: "8080"
  DBHOST: "34.101.132.209"
  DBNAME: "retail-intelligence"
  DBUSER: "nodeuser"
  DBPASSWORD: "rotikeju98"
  DBENGINE: "postgresql"