service: prod-retail-intelligence-api
runtime: nodejs12
instance_class: F4
env: standard
env_variables:
  PORT: "8080"
  DBHOST: ""
  DBNAME: ""
  DBUSER: ""
  DBPASSWORD: ""
  DBENGINE: "postgresql"
  APPLICATION_PORT: 8080